grails-app/domain/com/example/memsource/Configuration.groovy
package com.example.memsource

/*Authentication details for external rest api call*/
class Configuration {

    /*External Username for memsource api authentication*/
    String username

    /*Password for above user*/
    String password

    /*Token*/
    String token

    /*Token Expiry Date*/
    Date expiryDate


    static constraints = {
        username(nullable: false, blank: false)
        password(nullable: false, blank: false)
        token(nullable: true)
        expiryDate(nullable: true, validator: {val, obj ->
            if(obj.token && !obj.expiryDate){
                return "expiry.date.cannot.be.null"
            }
        })
    }
}

grails-app/controllers/com/example/memsource/ConfigurationController.groovy
package com.example.memsource


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ConfigurationController {

    def configurationService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index() {
        redirect(action: "show")
    }

    def show() {
        Configuration configuration = configurationService.fetchConfiguration()
        if(!configuration){
            configuration = new Configuration()
        }
        return [configuration: configuration]
    }

    @Transactional
    def save() {
        Configuration configuration = configurationService.fetchConfiguration()
        if(!configuration){
            configuration = new Configuration()
        }
        configuration.username = params.username
        configuration.password = params.password
        if(configuration.validate() && !configuration.hasErrors()){
            configuration.save(flush: true)
            redirect(action: "show")
        }else{
            render(view: "edit", model: [configuration: configuration])
        }
    }

    def edit() {
        Configuration configuration = configurationService.fetchConfiguration()
        if(!configuration){
            configuration = new Configuration()
        }
        return [configuration: configuration]
    }
}

grails-app/controllers/com/example/memsource/ProjectController.groovy
package com.example.memsource

class ProjectController {

    def configurationService
    def projectService

    def index() {
        Configuration configuration = configurationService.fetchConfiguration()
        if(!configuration){
            flash.errorMessage = "Please configure username and password first"
            redirect(controller: "configuration", action: "edit")
            return
        }
        return [projects: []]
    }

    def paginateProjects(){
        Integer page = 0
        if(params.page){
            page = Integer.parseInt(params?.page?.toString())
        }
        Configuration configuration = configurationService.fetchConfiguration()
        if(!configuration){
            flash.errorMessage = "Please configure username and password first"
            redirect(controller: "configuration", action: "edit")
            return
        }
        List<Map>  projects = projectService.fetchProjects(configuration, page)
        render(template: "list", model: [projects: projects])
    }
}

grails-app/views/configuration/_form.gsp
<%@ page import="com.example.memsource.Configuration" %>



<div class="fieldcontain ${hasErrors(bean: configuration, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="configuration.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" required="" value="${configuration?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: configuration, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="configuration.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:passwordField name="password" required="" value="${configuration?.password}"/>

</div>

grails-app/views/configuration/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'configuration.label', default: 'Configuration')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-configuration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-configuration" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${configurationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${configurationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:configurationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/configuration/edit.gsp
<%@ page import="com.example.memsource.Configuration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'configuration.label', default: 'Configuration')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-configuration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="edit-configuration" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:if test="${flash.errorMessage}">
			<div class="errors" role="status">${flash.errorMessage}</div>
			</g:if>
			<g:hasErrors bean="${configuration}">
			<ul class="errors" role="alert">
				<g:eachError bean="${configuration}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form controller="configuration" method="POST" >
				<g:hiddenField name="version" value="${configuration?.version}" />
				<fieldset class="form">
					<g:render template="form" model="[configuration: configuration]"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="save" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/configuration/index.gsp
<%@ page import="com.example.memsource.Configuration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'configuration.label', default: 'Configuration')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-configuration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-configuration" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'configuration.username.label', default: 'Username')}" />
					
						<g:sortableColumn property="password" title="${message(code: 'configuration.password.label', default: 'Password')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${configurationInstanceList}" status="i" var="configurationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${configurationInstance.id}">${fieldValue(bean: configurationInstance, field: "username")}</g:link></td>
					
						<td>${fieldValue(bean: configurationInstance, field: "password")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${configurationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/configuration/show.gsp
<%@ page import="com.example.memsource.Configuration" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'configuration.label', default: 'Configuration')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-configuration" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
			</ul>
		</div>
		<div id="show-configuration" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list configuration">
			
				<g:if test="${configuration?.username}">
				<li class="fieldcontain">
					<span id="username-label" class="property-label"><g:message code="configuration.username.label" default="Username" /></span>
					
						<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${configuration}" field="username"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${configuration?.password}">
				<li class="fieldcontain">
					<span id="password-label" class="property-label"><g:message code="configuration.password.label" default="Password" /></span>
					
						<span class="property-value" aria-labelledby="password-label"><g:fieldValue bean="${configuration}" field="password"/></span>
					
				</li>
				</g:if>
				<g:if test="${!configuration?.id}">
					<g:link class="create" action="edit">New</g:link>
				</g:if>
				<g:else>
					<g:link class="create" action="edit">Edit</g:link>
				</g:else>
			
			</ol>

		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/project/_list.gsp
<g:if test="${projects}">
<table>
    <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Source Language</th>
        <th>Target Language</th>
    </tr>
    <g:each in="${projects}" var="project">
        <tr>
            <td>${project.name}</td>
            <td>${project.status}</td>
            <td>${project.sourceLang}</td>
            <td>${project.targetLangs?.join(",")}</td>
        </tr>
    </g:each>
</table>
</g:if>
<g:else>
    <b>No Projects Found</b>
</g:else>

grails-app/views/project/index.gsp
<%@ page import="com.example.memsource.Configuration" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <title>Projects</title>
</head>
<body>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
    </ul>
</div>
<div id="listProjects" class="content scaffold-show" role="main">
    %{--<g:render template="list" model="[projects: projects]"/>--}%
</div>
<div>
    <label>Enter Page Number</label>
    <input type="text" id="pageNumber">
    <button onclick="getProjects()">Projects</button>
</div>
<script>
    function getProjects() {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
            if (xhttp.readyState == 4 && xhttp.status == 200) {
                document.getElementById("listProjects").innerHTML = xhttp.responseText;
            }
        };
        xhttp.open("GET", "${g.createLink(controller: 'project', action: 'paginateProjects')}?page="+document.getElementById("pageNumber").value, true);
        xhttp.send();
    }
</script>
</body>
</html>